### ISSUE TITLE
REGEX mis-matches

### ISSUE THREAD

**Issue by IamSanjid** [andrewCodeDev/Fluent#21]
`foo(\.json\.(\d+)|\.|-\d+).*` this pattern is matching for `foo-bar-18.random` string also for `foo-bar-18.json`
according PCRE format it's not supposed to.

Nice project btw! Really needed something like this.

**Comment by andrewCodeDev** [comment]
Thanks for the bug report. I pushed a change for a missing check for an escaped character. Please try that and tell me how that turns out (updated latest package to v.2.2.3). According to my tests, it now doesn't match either in accordance with prce syntax.

**Comment by IamSanjid** [comment]
> Thanks for the bug report. I pushed a change for a missing check for an escaped character. Please try that and tell me how that turns out (updated latest package to v.2.2.3). According to my tests, it now doesn't match either in accordance with prce syntax.

Awesome thanks for the quick fix!
