### ISSUE TITLE
return the multiplicative identity element (1) when acting on empty slices

### ISSUE THREAD

**Issue by dimdin** [andrewCodeDev/Fluent#6]
https://github.com/andrewCodeDev/Fluent/blob/c1300bdce30e83dbd214717a2d51f047bf1dabb8/fluent.zig#L216-L219
return the multiplicative identity element (1) when acting on empty slices

**Comment by andrewCodeDev** [comment]
We can actually remove that check and let the initial value fall through to the return (it gets initialized as 1) - done.
