### ISSUE TITLE
Examine both types for generic binary operations return type

### ISSUE THREAD

**Issue by dimdin** [andrewCodeDev/Fluent#7]
https://github.com/andrewCodeDev/Fluent/blob/c1300bdce30e83dbd214717a2d51f047bf1dabb8/fluent.zig#L1205-L1217

`@TypeOf(x, y)` is better for return type.

The result is the same if the types are the same.
Example: `x: i32, y: i64`, `@TypeOf(x)` returns i32, but `@TypeOf(x, y)` returns i64.

**Comment by andrewCodeDev** [comment]
Got it - thanks.
